###############################################################################
#
# Copyright 2021 NVIDIA Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
###############################################################################

- name: Deploy DOCA Service Containers for Morpheus
  hosts: dpus
  gather_facts: true
  become: true
  tasks:
    # set key variables here. Overrides role vars
    - name: Set Variables
      set_fact:
        #-> arbitrary number for new trusted sf for flow inspector
        sf_num: 44
        #
        #-> the interface we wish to mirror/monitor with flow inspector
        monitor_interface: p0
        #
        #-> The hostname or ip and port of aggregator. 
        #-> Can also be set in role vars
        fluentd_aggregator_host: 192.168.100.1
        fluentd_aggregator_port: 32522

    - name: Check for existing DOCA Telemetry Standalone
      stat:
        path: /etc/kubelet.d/doca_telemetry_standalone.yaml
      register: stat_result

    # When doca_telemetry_standalone.yml is present in /etc/kubelet.d
    # modify yaml file for morpheus
    - name: Update doca telemetry container init command for morpheus(fluentd)
      replace:
        path: "/etc/kubelet.d/doca_telemetry_standalone.yaml"  # noqa 204
        regexp: '/usr/bin/enable-fluent-forward.sh.*'
        replace: '/usr/bin/enable-fluent-forward.sh {{ fluentd_aggregator_host }} {{ fluentd_aggregator_port }}"]'
      when: stat_result.stat.exists

    - name: Restart the pod if using the existing DTS
      shell: crictl stopp `crictl pods | grep doca-telemetry-service-localhost.localdomain | cut -d' ' -f1`
      when: stat_result.stat.exists

#    - name: Restart kubelet
#      systemd:
#        name: kubelet
#        state: restarted
  
    - name: Role - install_ngc_cli
      include_role:
        name: install_ngc_cli

    - name: Role - ngc_containerd_setup
      include_role:
        name: ngc_containerd_setup

    # When doca_telemetry_standalone.yaml is not present in /etc/kubelet.d/
    # deploy the service from NGC using the role
    - name: Role - deploy_doca_telemetry_container
      include_role:
        name: deploy_doca_telemetry_container
      when: not stat_result.stat.exists

    - name: Role - deploy_doca_flow_inspector_container
      include_role:
        name: deploy_doca_flow_inspector_container
