### Testing Multiple DPUs in an x86

l_csi_0333d_dpus:
  # _ dpu_oob
  # _ dpu_oob2
  - l_csi_bf2_25g_12
  - l_csi_bf2_25g_04

chrony_timezone: "America/Los_Angeles"

### SFC Enabled ###

# sfcenabled: true

### BF Firmwave Update Workflow ###

# bffwupdate: true

### DOCA IMAGES AND URLS ###

# DOCA 1.5.1 / BFB 3.9.3:
# Production / Signed Image:
doca_bfb: "DOCA_1.5.1_BSP_3.9.3_Ubuntu_20.04-4.2211-LTS.signed.bfb"
bfb_download_url: "http://www.mellanox.com/downloads/BlueField/BFBs/Ubuntu20.04/{{ doca_bfb }}"
# Development / Unsigned Image:
dev_doca_bfb: "DOCA_1.5.1_BSP_3.9.3_Ubuntu_20.04-4.2211-LTS.bfb"
dev_bfb_download_url: "http://www.mellanox.com/downloads/BlueField/BFBs/Ubuntu20.04/{{ dev_doca_bfb }}"
# DOCA 1.5.0 / BFB 3.9.3:
# Production / Signed Image:
# doca_bfb: 'DOCA_1.5.0_BSP_3.9.3_Ubuntu_20.04-11.signed.bfb'
# bfb_download_url: 'http://www.mellanox.com/downloads/BlueField/BFBs/Ubuntu20.04/{{ doca_bfb }}'
# Development / Unsigned Image:
# dev_doca_bfb: 'DOCA_1.5.0_BSP_3.9.3_Ubuntu_20.04-11.bfb'
# dev_bfb_download_url: 'http://www.mellanox.com/downloads/BlueField/BFBs/Ubuntu20.04/{{ dev_doca_bfb }}'
# DOCA 1.4.0 / BFB 3.9.2:
# doca_bfb: 'DOCA_1.4.0_BSP_3.9.2_Ubuntu_20.04-4.signed.bfb'
# bfb_download_url: 'http://www.mellanox.com/downloads/BlueField/BFBs/Ubuntu20.04/{{ doca_bfb }}'
# Development / Unsigned Image:
# dev_doca_bfb: 'DOCA_1.4.0_BSP_3.9.2_Ubuntu_20.04-4.bfb'
# dev_bfb_download_url: 'http://www.mellanox.com/downloads/BlueField/BFBs/Ubuntu20.04/{{ dev_doca_bfb }}'
# DOCA 1.3.0 / BFB 3.9.0:
# doca_bfb: 'DOCA_1.3.0_BSP_3.9.0_Ubuntu_20.04-6.signed.bfb'
# DOCA 1.2.1 / BFB 3.8.5:
# doca_bfb: "DOCA_v1.2.1_BlueField_OS_Ubuntu_20.04-5.4.0-1023-bluefield-5.5-2.1.7.0-3.8.5.12027-1.signed-aarch64.bfb"
# DOCA 1.2 / BFB 3.8.0:
# doca_bfb: "DOCA_v1.2.0_BlueField_OS_Ubuntu_20.04-5.4.0-1022-bluefield-5.5-1.0.3.2-3.8.0.11969-1.signed-aarch64.bfb"
# DOCA 1.1 / BFB 3.7.1:
# doca_bfb: "DOCA_v1.1_BlueField_OS_Ubuntu_20.04-5.4.0-1017.17.gf565efa-bluefield-5.4-2.4.1.3-3.7.1.11866-2.signed-aarch64.bfb"
#
