
# These vars can be provided here, but are normally prompted for and set as facts elsewhere in playbook
#
# ngc_team: ""
# ngc_api_key: ""
# ngc_org: ""

# Checks for ngc cli and only installs if absent
# to force an instal, set to true
force_install_ngc_cli: false
# Only configures ngc if theres no api key detected
# force a config push, set to true
force_configure_ngc: false
