###############################################################################
#
# Copyright 2021 NVIDIA Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
###############################################################################
- name: Start Mellanox Software Tools (mst)  # noqa 305
  shell: "mst start"
  changed_when: false
  # [305] Use shell only when shell functionality is required

- name: Detecting if we are already in embedded mode
  shell: mlxconfig -d /dev/mst/mt41686_pciconf0 -e q INTERNAL_CPU_MODEL | grep "INTERNAL_CPU_MODEL" | tr -s ' ' | cut -d' ' -f4
  register: mode_check_output

- when: mode_check_output.stdout == "EMBEDDED_CPU(1)"
  block:
    - name: Embedded Mode already detected
      debug:
        msg: "Embedded Mode already detected. Skipping"

    - name: Set flag already enabled
      set_fact:
        embedded_mode_enabled: true

- when: embedded_mode_enabled is false
  block:
    - name: Grep BF device
      shell: "set -o pipefail && mst status | grep -i '/dev/' | awk -F ' ' '{print $1}'" # noqa 305
      args:
        executable: /usr/bin/bash
      register: grep_output
      changed_when: false
  # [305] Use shell only when shell functionality is required

    - name: Enable Embedded Mode  # noqa 305 301
      shell: "{{ item }}"
      with_items:
        - "mlxconfig -y -d {{ grep_output.stdout }} s INTERNAL_CPU_MODEL=1 "
        - "mlxconfig -y -d {{ grep_output.stdout }}.1 s INTERNAL_CPU_MODEL=1 "

    - name: Set reboot_needed flag
      set_fact:
        reboot_needed: true
