###############################################################################
#
# Copyright 2021 NVIDIA Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
###############################################################################
#
# The URL filter container does not need SFs to start.
# You have to start the interactive app from inside the container
# That means we don't have to update the container yaml file with the aux device numbers
# but you still need two SFs connected properly to OVS
#
# use mlnx-sf -a show to find the aux devices for the SF numbers when going to start the app in the container

- name: Ask for host interface
  pause:
    prompt: Connect container to which host interface (on DPU)
  register: host_interface_input
  when: host_interface is undefined or host_interface|length < 6

- name: Get host_interface from prompt
  set_fact:
    host_interface: "{{ host_interface_input['user_input'] }}"
  when: not host_interface_input.skipped

# Create two SFs for this container
- name: Create two SFs
  include_role:
    name: create_sf_pair

# enable hugepages
- name: Enable 2048k hugepages
  shell: echo 2048 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
  changed_when: false

# ensure mlx-regex service is started
- name: Ensure mlx-regex service is started
  systemd:
    name: mlx-regex
    state: started

## Work on the container yaml file for kubelet
- name: Check if resources are already downloaded
  command: ngc registry resource info {{ container_resources_path }}
  register: container_config_info
  changed_when: false

- name: check version
  set_fact:
    container_resources_version: "{{ (container_config_info.stdout|from_json).latestVersionIdStr }}"

- name: Pull container resources files
  command:
    cmd: ngc registry resource download-version {{ container_resources_path }}
    creates: /tmp/doca_container_configs_v{{ container_resources_version }}
    chdir: /tmp
  register: container_config_download

# copy yaml file to kublet
- name: Copy yaml file to kubelet.d
  command: cp "/tmp/doca_container_configs_v{{ container_resources_version }}/configs/{{ container_resources_version|regex_replace('([1-2].[0-9]).[0-9]', '\1') }}/doca_url_filter.yaml" /etc/kubelet.d/doca_url_filter.yaml  # noqa 204
  changed_when: false
  # [204] Lines should be no longer than 160 chars

- name: Ensure kubelet is started
  systemd:
    name: kubelet
    state: started

- name: Output instructions
  debug:
    msg: check "mlnx-sf -a show" output for SF/Aux device info
