###############################################################################
#
# Copyright 2021 NVIDIA Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
###############################################################################
# DOCA 1.5.0 / BFB 3.9.3:
# Production / Signed Image:
doca_bfb: 'DOCA_1.5.0_BSP_3.9.3_Ubuntu_20.04-11.signed.bfb'
bfb_download_url: 'http://www.mellanox.com/downloads/BlueField/BFBs/Ubuntu20.04/{{ doca_bfb }}'
# Development / Unsigned Image:
dev_doca_bfb: 'DOCA_1.5.0_BSP_3.9.3_Ubuntu_20.04-11.bfb'
dev_bfb_download_url: 'http://www.mellanox.com/downloads/BlueField/BFBs/Ubuntu20.04/{{ dev_doca_bfb }}'
# DOCA 1.4.0 / BFB 3.9.2:
# Production / Signed Image:
# doca_bfb: 'DOCA_1.4.0_BSP_3.9.2_Ubuntu_20.04-4.signed.bfb'
# bfb_download_url: 'http://www.mellanox.com/downloads/BlueField/BFBs/Ubuntu20.04/{{ doca_bfb }}'
# Development / Unsigned Image:
# dev_doca_bfb: 'DOCA_1.4.0_BSP_3.9.2_Ubuntu_20.04-4.bfb'
# dev_bfb_download_url: 'http://www.mellanox.com/downloads/BlueField/BFBs/Ubuntu20.04/{{ dev_doca_bfb }}'
