- name: Reset vars
  set_fact:
    discover_physical_function: false

- name: Check if we need to autodetect physical function(s)
  set_fact:
    discover_physical_function: true
  when: physical_function is undefined

- name: build list of physical functions
  set_fact:
    physical_function: "{{ physical_function|default([]) + [hostvars[inventory_hostname]['ansible_' + item].device] }}"
  when:
    - discover_physical_function
    - hostvars[inventory_hostname]['ansible_' + item].module is defined
    - hostvars[inventory_hostname]['ansible_' + item].module is search("mlx5_core")
    - hostvars[inventory_hostname]['ansible_' + item].device is not regex("en.*v.*")
  with_items: "{{ ansible_interfaces }}"

- name: Create VFs
  shell: echo 0 > /sys/class/net/{{ item }}/device/sriov_numvfs
  with_items: "{{ physical_function }}"
  changed_when: false

- name: Create VFs
  shell: echo {{ num_vfs }} > /sys/class/net/{{ item }}/device/sriov_numvfs
  with_items: "{{ physical_function }}"
  changed_when: false
