###############################################################################
#
# Copyright 2021 NVIDIA Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
###############################################################################

- name: Production DOCA Image install
  block:
    - name: Board Type Annoucement
      debug:
        msg: 'Install on a Production DPU commencing'

    - name: Checking if BFB has been downloaded
      stat:
        path: '/tmp/{{ doca_bfb }}'
      register: bfbdownload

    - name: Download bfb from the Internet
      get_url:
        url: '{{ bfb_download_url }}'
        dest: '/tmp'
      when: not bfbdownload.stat.exists

    - name: Role - build_bfb_cfg
      import_role:
        name: build_bfb_cfg

    - name: Stop rshim, if running
      ansible.builtin.systemd:
        name: rshim
        state: stopped

    - name: Start rshim, if running
      ansible.builtin.systemd:
        name: rshim
        state: started

    - name: Pause 30 seconds for rshim
      pause:
        seconds: 30

    - name: Load bfb into bf2...this will take a while # noqa 305
      shell: 'bfb-install --bfb /tmp/{{ doca_bfb }} --config /tmp/bf.cfg --rshim rshim{{ rshim_num }}'
      changed_when: false

    - name: Remove bf.cfg file
      file:
        path: /tmp/bf.cfg
        state: absent

    # this drops an ssh client config file that allows you to do 'ssh rshim0' or 'ssh rshim1' and use the ipv6 link local addresses
    - name: Ensure ssh config file is in place
      template:
        src: rshimX.conf.j2
        dest: /etc/ssh/ssh_config.d/rshim{{ rshim_num }}.conf
        mode: 0644

    - name: Pause for 5 minutes - DPU needs to catch its breath
      pause:
        minutes: 5

  when: board is not defined

- name: Development DOCA Image install
  block:
    - name: Board Type Annoucement
      debug:
        msg: 'Install on a Development DPU commencing'

    - name: Checking if BFB has been downloaded
      stat:
        path: '/tmp/{{ dev_doca_bfb }}'
      register: bfbdownload

    - name: Download bfb from the Internet
      get_url:
        url: '{{ dev_bfb_download_url }}'
        dest: '/tmp'
      when: not bfbdownload.stat.exists

    - name: Role - build_bfb_cfg
      import_role:
        name: build_bfb_cfg

    - name: Stop rshim, if running
      ansible.builtin.systemd:
        name: rshim
        state: stopped

    - name: Start rshim, if running
      ansible.builtin.systemd:
        name: rshim
        state: started

    - name: Pause 30 seconds for rshim
      pause:
        seconds: 30

    - name: Load bfb into bf2...this will take a while # noqa 305
      shell: 'bfb-install --bfb /tmp/{{ dev_doca_bfb }} --config /tmp/bf.cfg --rshim rshim{{ rshim_num }}'
      changed_when: false

    - name: Remove bf.cfg file
      file:
        path: /tmp/bf.cfg
        state: absent

    # this drops an ssh client config file that allows you to do 'ssh rshim0' or 'ssh rshim1' and use the ipv6 link local addresses
    - name: Ensure ssh config file is in place
      template:
        src: rshimX.conf.j2
        dest: /etc/ssh/ssh_config.d/rshim{{ rshim_num }}.conf
        mode: 0644

    - name: Pause for 5 minutes - DPU needs to catch its breath
      pause:
        minutes: 5

  when:
    - board is defined
    - board == 'dev'
